name: Verify
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: rubysg-reboot
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      DATABASE_URL: postgresql://rubysg-reboot:password@localhost/rubysg-reboot_test?pool=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
          bundler-cache: true

      - name: Install Ruby dependencies
        run: bundle install

      - name: Set up test database
        run: bin/rails db:test:prepare

      - name: Run tests
        run: bin/rake
